Repository YAPP-admin/attendance-ios, pull requests merged in 2022-05, with the labels that each got.

#70 관리자용 화면 UI, Remote Config, 및 누적 출결 점수 로직 구현
  attendance-ios.xcodeproj/project.pbxproj
  attendance-ios/Resource/Assets.xcassets/icon/logout.imageset/Contents.json
  attendance-ios/Resource/Assets.xcassets/icon/logout.imageset/logout.png
  attendance-ios/Resource/Assets.xcassets/icon/logout.imageset/logout@2x.png
  attendance-ios/Resource/Assets.xcassets/icon/logout.imageset/logout@3x.png
  attendance-ios/Source/Admin/AdminViewModel.swift
  attendance-ios/Source/Admin/Grade/AdminGradeCell.swift
  attendance-ios/Source/Admin/Grade/AdminGradeMemberCell.swift
  attendance-ios/Source/Admin/Grade/AdminGradeViewController.swift
  attendance-ios/Source/Admin/Main/AdminSessionCell.swift
  attendance-ios/Source/Admin/Main/AdminTodayView.swift
  attendance-ios/Source/Admin/Main/AdminViewController.swift
  attendance-ios/Source/Admin/Management/AdminBottomSheetCell.swift
  attendance-ios/Source/Admin/Management/AdminBottomSheetView.swift
  attendance-ios/Source/Admin/Management/AdminManagementCell.swift
  attendance-ios/Source/Admin/Management/AdminManagementMemberCell.swift
  attendance-ios/Source/Admin/Management/AdminManagementViewController.swift
  attendance-ios/Source/Common/BaseViewModel.swift
  attendance-ios/Source/Common/PrintFn.swift
  attendance-ios/Source/Extensions/Foundation/Array.swift
  attendance-ios/Source/Extensions/Foundation/Date.swift
  attendance-ios/Source/Extensions/Models/Member.swift
  attendance-ios/Source/Extensions/Models/Session.swift
  attendance-ios/Source/Extensions/Models/Team.swift
  attendance-ios/Source/Extensions/UIKit/UICollectionViewCell.swift
  attendance-ios/Source/Extensions/UIKit/UIColor.swift
  attendance-ios/Source/Extensions/UIKit/UIFont.swift
  attendance-ios/Source/Extensions/UIKit/UILabel.swift
  attendance-ios/Source/Extensions/UIKit/UIStackView.swift
  attendance-ios/Source/Extensions/UIKit/UIString.swift
  attendance-ios/Source/Extensions/UIKit/UITextField.swift
  attendance-ios/Source/Extensions/UIKit/UIView.swift
  attendance-ios/Source/Extensions/UIKit/UIViewController.swift
  attendance-ios/Source/Extensions/UIView.swift
  attendance-ios/Source/Home/HomeViewController.swift
  attendance-ios/Source/Login/LoginViewController.swift
  attendance-ios/Source/Model/Attendance.swift
  attendance-ios/Source/Model/Models.swift
  attendance-ios/Source/SignUp/SignUpPositionViewController.swift
  attendance-ios/Source/Utilities/ConfigWorker.swift
  attendance-ios/Source/Utilities/FirebaseWorker.swift
Labels: 관리자용 화면, 파이어베이스

#72 관리자용 화면
  attendance-ios.xcodeproj/project.pbxproj
  attendance-ios/Source/Admin/AdminViewModel.swift
  attendance-ios/Source/Admin/Common/AdminMessageHeader.swift
  attendance-ios/Source/Admin/Common/AdminMessageView.swift
  attendance-ios/Source/Admin/Grade/AdminGradeCell.swift
  attendance-ios/Source/Admin/Grade/AdminGradeMemberCell.swift
  attendance-ios/Source/Admin/Grade/AdminGradeViewController.swift
  attendance-ios/Source/Admin/Main/AdminCardView.swift
  attendance-ios/Source/Admin/Main/AdminViewController.swift
  attendance-ios/Source/Admin/Management/AdminManagementCell.swift
  attendance-ios/Source/Admin/Management/AdminManagementMemberCell.swift
  attendance-ios/Source/Admin/Management/AdminManagementViewController.swift
  attendance-ios/Source/Extensions/Models/Attendances.swift
  attendance-ios/Source/Extensions/UIKit/UICollectionReusableView.swift
  attendance-ios/Source/Model/Models.swift
  attendance-ios/Source/Utilities/FirebaseWorker.swift
Labels: 관리자용 화면, 파이어베이스

#71 #65, #66 멤버용 - 홈 데이터 연동
  attendance-ios/Source/Home/HomeAttendanceCheckTableViewCell.swift
  attendance-ios/Source/Home/HomeAttendanceCheckViewController.swift
  attendance-ios/Source/Home/HomeAttendanceDetailViewController.swift
  attendance-ios/Source/Home/HomeChartView.swift
  attendance-ios/Source/Home/HomeTotalScoreTableViewCell.swift
  attendance-ios/Source/Home/HomeViewController.swift
  attendance-ios/Source/Home/HomeViewModel.swift
  attendance-ios/Source/Setting/SettingViewController.swift
  attendance-ios/Source/Setting/SettingViewModel.swift
  attendance-ios/Source/Utilities/FirebaseWorker.swift
  attendance-ios/Source/Utilities/UserDefaultsWorker.swift
Labels: 기능 추가, 홈 화면, 점수 화면

#73 설정 화면에서 회원 탈퇴, 로그아웃 연결
  attendance-ios/Source/Setting/SettingViewController.swift
  attendance-ios/Source/Setting/SettingViewModel.swift
  attendance-ios/Source/Utilities/FirebaseWorker.swift
  attendance-ios/Source/Utilities/UserDefaultsWorker.swift
Labels: 설정 화면

#78 #77 설정 화면에서 회원 탈퇴
  attendance-ios/Source/Setting/SettingViewController+UI.swift
  attendance-ios/Source/Setting/SettingViewController.swift
  attendance-ios/Source/Setting/SettingViewModel.swift
  attendance-ios/Source/SignUp/SignUpNameViewController.swift
  attendance-ios/Source/SignUp/SignUpPositionViewController.swift
  attendance-ios/Source/SignUp/SignUpTeamViewController.swift
Labels: 설정 화면, 기능 개선

#80 #75 로그인
  attendance-ios/Source/Common/BaseViewModel.swift
  attendance-ios/Source/Setting/SettingViewModel.swift
  attendance-ios/Source/SignUp/SignUpViewModel.swift
  attendance-ios/Source/Utilities/FirebaseWorker.swift
Labels: 로그인 화면, 회원가입 화면, 기능 개선

#82 #76 다크모드 막음
  attendance-ios/Resource/Info.plist
Labels: 기능 개선

#83 #36 개인정보처리방침 추가
  attendance-ios/Source/Extensions/UIKit/UIViewController.swift
  attendance-ios/Source/Home/HomeAttendanceCheckViewController.swift
  attendance-ios/Source/Home/HomeTotalScoreTableViewCell.swift
  attendance-ios/Source/Home/HomeViewController.swift
  attendance-ios/Source/Home/HomeViewModel.swift
  attendance-ios/Source/QR/QRViewController.swift
  attendance-ios/Source/QR/QRViewModel.swift
  attendance-ios/Source/Setting/SettingCellView.swift
  attendance-ios/Source/Setting/SettingPrivacyPolicyViewController.swift
Labels: 기능 추가, 버그, 설정 화면, 점수 화면

#86 #85 관리자용 화면에서 점수 계산 로직 수정
  attendance-ios.xcodeproj/project.pbxproj
  attendance-ios/Source/Admin/Grade/AdminGradeCell.swift
  attendance-ios/Source/Admin/Grade/AdminGradeMemberCell.swift
  attendance-ios/Source/Admin/Grade/AdminGradeViewController.swift
  attendance-ios/Source/Extensions/Models/Member.swift
Labels: 관리자용 화면, 기능 개선

#89 #88 출결 화면 이동 셀 클릭 범위 수정
  attendance-ios/Source/Admin/Main/AdminSessionCell.swift
  attendance-ios/Source/Admin/Main/AdminViewController.swift
Labels: 관리자용 화면, 기능 개선

#91 #87 관리자용 - 하단 시트 애니메이션
  attendance-ios/Source/Admin/Management/AdminBottomSheetView.swift
  attendance-ios/Source/Admin/Management/AdminManagementViewController.swift
Labels: 관리자용 화면, 기능 개선

#113 #103 로그인 - 이스터에그 뷰 수정
  attendance-ios/Source/Common/BaseViewModel.swift
  attendance-ios/Source/Login/EasterEggView.swift
  attendance-ios/Source/Login/LoginViewController.swift
Labels: 기능 추가, 로그인 화면

#115 회원가입 UI 수정
  attendance-ios/Source/Extensions/UIKit/UIViewController.swift
  attendance-ios/Source/Setting/SettingViewController.swift
  attendance-ios/Source/SignUp/SignUpNameViewController.swift
  attendance-ios/Source/SignUp/SignUpPositionViewController.swift
  attendance-ios/Source/SignUp/SignUpTeamViewController.swift
Labels: 회원가입 화면

#116 #105 로그인에 실패한 경우 실패 토스트 띄움
  attendance-ios/Source/Common/BaseViewModel.swift
  attendance-ios/Source/Login/LoginViewController.swift
Labels: 기능 추가, 로그인 화면

#117 #107 로그인 - 자동 로그인일 때 스플래시 화면 표시
  attendance-ios/Source/Common/BaseViewModel.swift
  attendance-ios/Source/Home/HomeViewModel.swift
  attendance-ios/Source/Login/LoginViewController.swift
  attendance-ios/Source/Setting/SettingViewModel.swift
  attendance-ios/Source/System/SceneDelegate.swift
  attendance-ios/Source/Utilities/UserDefaultsWorker.swift
Labels: 로그인 화면, 기능 개선

#119 #94 로그인 - 로딩 화면 추가
  attendance-ios/Source/Common/BaseViewModel.swift
  attendance-ios/Source/Extensions/UIKit/UIViewController.swift
  attendance-ios/Source/Login/LoginViewController.swift
Labels: 기능 추가, 로그인 화면

#120 로그인 - 키보드가 이스터 에그창을 가릴 경우 처리
  attendance-ios/Source/Login/EasterEggView.swift
  attendance-ios/Source/Login/LoginViewController.swift
Labels: 로그인 화면, 기능 개선

#121 #101 네비게이션바 height 수정
  attendance-ios/Source/Admin/Main/AdminViewController.swift
  attendance-ios/Source/Extensions/UIKit/UIViewController.swift
  attendance-ios/Source/Home/HelpViewController.swift
  attendance-ios/Source/Home/HomeAttendanceDetailViewController.swift
  attendance-ios/Source/Setting/SettingViewController+UI.swift
Labels: 기능 개선

#122 #74 관리자용 - 출결 변경시 문서 업데이트 안되는 문제 해결
  attendance-ios/Source/Utilities/FirebaseWorker.swift
Labels: 관리자용 화면, 파이어베이스, 기능 개선

#123 #95 개인정보처리방침 Loading 추가, #32 QR 데이터 연동 완료
  attendance-ios/Source/Extensions/UIKit/UIViewController.swift
  attendance-ios/Source/Home/HomeTotalScoreTableViewCell.swift
  attendance-ios/Source/Home/HomeViewController.swift
  attendance-ios/Source/Home/HomeViewModel.swift
  attendance-ios/Source/QR/QRViewController.swift
  attendance-ios/Source/QR/QRViewModel.swift
  attendance-ios/Source/Setting/SettingPrivacyPolicyViewController.swift
  attendance-ios/Source/Setting/SettingViewModel.swift
  attendance-ios/Source/SignUp/SignUpPositionViewController.swift
  attendance-ios/Source/SignUp/SignUpTeamViewController.swift
  attendance-ios/Source/SignUp/SignUpViewModel.swift
Labels: 기능 추가, 설정 화면, 기능 개선

#125 #118 스플래시 배경색 설정
  attendance-ios/Resource/Image/splash_login.html
  attendance-ios/Source/Login/LoginViewController.swift
  attendance-ios/Source/Storyboards/Base.lproj/LaunchScreen.storyboard
Labels: 로그인 화면, 기능 개선

#127 #124 뒤로가기 버튼 클릭 잘 안되는 부분 수정
  attendance-ios/Source/Login/LoginViewController.swift
  attendance-ios/Source/SignUp/SignUpNameViewController.swift
  attendance-ios/Source/SignUp/SignUpPositionViewController.swift
  attendance-ios/Source/SignUp/SignUpTeamViewController.swift
Labels: 버그, 회원가입 화면

#129 #100 점수화면 - 도움말 UI 수정 필요
  attendance-ios/Source/Extensions/UIKit/UILabel.swift
  attendance-ios/Source/Home/HelpViewController.swift
Labels: 설정 화면, 기능 개선

#133 #132 오늘 세션의 관리 버튼이 안눌리는 문제 해결
  attendance-ios/Source/Admin/Main/AdminTodayView.swift
  attendance-ios/Source/Admin/Main/AdminViewController.swift
Labels: 버그, 관리자용 화면

#135 #134 뒤로가기 클릭시 네비게이션바 배경색상이 보이는 문제 해결
  attendance-ios/Source/Extensions/UIKit/UIViewController.swift
Labels: 회원가입 화면, 기능 개선

#136 #130 다시 로그인 진입시 스플래시의 주황 배경이 잠깐 보이는 문제 해결
  attendance-ios/Source/Login/LoginViewController.swift
Labels: 로그인 화면, 기능 개선

#137 #96 오류 발생 일러스트 이미지 추가
  attendance-ios/Resource/Assets.xcassets/illust/illust_error.imageset/illust_error.png
  attendance-ios/Resource/Assets.xcassets/illust/illust_error.imageset/illust_error@2x.png
  attendance-ios/Resource/Assets.xcassets/illust/illust_error.imageset/illust_error@3x.png
  attendance-ios/Source/Home/HomeViewController.swift
  attendance-ios/Source/Home/HomeViewModel.swift
Labels: 홈 화면

#138 #102 홈 - 상단에 refresh indicator 추가
  attendance-ios/Source/Home/HomeViewController.swift
  attendance-ios/Source/Home/HomeViewModel.swift
Labels: 기능 추가, 홈 화면

#140 #99 모든 세션을 끝마쳤습니다 표시
  attendance-ios/Source/Home/HomeViewController.swift
Labels: 기능 추가, 홈 화면
