Repository YAPP-admin/attendance-ios, pull requests merged in 2022-04, with the labels that each got.

#38 #37 파이어베이스 모델 변경사항 적용
  attendance-ios.xcodeproj/project.pbxproj
  attendance-ios/Source/Model/Attendance.swift
  attendance-ios/Source/Model/Models.swift
  attendance-ios/Source/SignUp/SignUpTeamInfoViewController.swift
  attendance-ios/Source/SignUp/SignUpViewModel.swift
Labels: 파이어베이스, 기능 개선

#41 Config 작성
  attendance-ios/Source/Model/Config.swift
  attendance-ios/Source/SignUp/SignUpTeamInfoViewController.swift
  attendance-ios/Source/SignUp/SignUpViewModel.swift
Labels: 파이어베이스

#40 #10 관리자용 화면 구현 중간단계
  attendance-ios.xcodeproj/project.pbxproj
  attendance-ios/Resource/Assets.xcassets/image/illust_check_grade.imageset/Contents.json
  attendance-ios/Resource/Assets.xcassets/image/illust_check_grade.imageset/illust_check_grade.png
  attendance-ios/Resource/Assets.xcassets/image/illust_check_grade.imageset/illust_check_grade@2x.png
  attendance-ios/Resource/Assets.xcassets/image/illust_check_grade.imageset/illust_check_grade@3x.png
  attendance-ios/Source/Admin/AdminViewModel.swift
  attendance-ios/Source/Admin/Common/AdminMessageView.swift
  attendance-ios/Source/Admin/Grade/AdminGradeViewController.swift
  attendance-ios/Source/Admin/Main/AdminCardView.swift
  attendance-ios/Source/Admin/Main/AdminSessionCell.swift
  attendance-ios/Source/Admin/Main/AdminTodayView.swift
  attendance-ios/Source/Admin/Main/AdminViewController.swift
  attendance-ios/Source/Admin/Management/AdminBottomSheetView.swift
  attendance-ios/Source/Admin/Management/AdminManagementViewController.swift
  attendance-ios/Source/BaseViewModel.swift
  attendance-ios/Source/Common/AlertView.swift
  attendance-ios/Source/Extensions/UIStackView.swift
  attendance-ios/Source/Extensions/UIView.swift
  attendance-ios/Source/Login/LoginViewController.swift
  attendance-ios/Source/Model/Config.swift
  attendance-ios/Source/SignUp/SignUpCollectionViewCell.swift
  attendance-ios/Source/SignUp/SignUpNameInfoViewController.swift
  attendance-ios/Source/SignUp/SignUpTeamInfoViewController.swift
  attendance-ios/Source/SignUp/SignUpViewModel.swift
Labels: 관리자용 화면

#42 #29 회원가입에서 직군 선택 화면 추가, ConfigWorker 클래스 생성
  attendance-ios.xcodeproj/project.pbxproj
  attendance-ios/Source/Extensions/UIView.swift
  attendance-ios/Source/Login/LoginViewController.swift
  attendance-ios/Source/Model/Config.swift
  attendance-ios/Source/Model/Models.swift
  attendance-ios/Source/SignUp/CollectionViewLeftAlignFlowLayout.swift
  attendance-ios/Source/SignUp/SignUpCollectionViewCell.swift
  attendance-ios/Source/SignUp/SignUpNameViewController.swift
  attendance-ios/Source/SignUp/SignUpPositionViewController.swift
  attendance-ios/Source/SignUp/SignUpTeamViewController.swift
  attendance-ios/Source/SignUp/SignUpViewModel.swift
  attendance-ios/Source/Utilities/ConfigWorker.swift
Labels: 회원가입 화면, 파이어베이스, 기능 개선

#49 파이어베이스, 카카오톡 로그인 관리 클래스 구현, 데이터 삭제 기능 추가, 이미 가입한 유저인지 체크
  attendance-ios.xcodeproj/project.pbxproj
  attendance-ios/Source/BaseViewModel.swift
  attendance-ios/Source/SignUp/SignUpViewModel.swift
  attendance-ios/Source/Utilities/FirebaseWorker.swift
  attendance-ios/Source/Utilities/KakaoLoginWorker.swift
Labels: 로그인 화면, 회원가입 화면, 파이어베이스

#53 뷰컨트롤러 init 오류 해결
  attendance-ios/Source/SignUp/SignUpNameViewController.swift
Labels: 버그, 회원가입 화면

#54 #52 회원가입, 로그인 기능 개선
  attendance-ios/Source/BaseViewModel.swift
  attendance-ios/Source/Login/LoginViewController.swift
  attendance-ios/Source/Model/Attendance.swift
  attendance-ios/Source/Model/Models.swift
  attendance-ios/Source/SignUp/SignUpTeamViewController.swift
  attendance-ios/Source/SignUp/SignUpViewModel.swift
  attendance-ios/Source/Utilities/FirebaseWorker.swift
  attendance-ios/Source/Utilities/UserDefaultsWorker.swift
Labels: 로그인 화면, 회원가입 화면, 파이어베이스

#55 #34 멤버용 - 설정 UI 구현
  attendance-ios.xcodeproj/project.pbxproj
  attendance-ios/Resource/Assets.xcassets/icon/qr.imageset/Contents.json
  attendance-ios/Source/Extensions/UIFont.swift
  attendance-ios/Source/Extensions/UILabel.swift
  attendance-ios/Source/Extensions/UIViewController.swift
  attendance-ios/Source/Home/HomeBottomTabView.swift
  attendance-ios/Source/Home/HomeViewController.swift
  attendance-ios/Source/Home/HomeViewModel.swift
  attendance-ios/Source/QR/QRViewController.swift
  attendance-ios/Source/Setting/SettingCellView.swift
  attendance-ios/Source/Setting/SettingViewController+UI.swift
  attendance-ios/Source/Setting/SettingViewController.swift
  attendance-ios/Source/Setting/SettingViewModel.swift
Labels: 설정 화면

#56 #9 멤버용 - 메인 화면 - 점수 체계 UI 화면 구조 구현
  attendance-ios.xcodeproj/project.pbxproj
  attendance-ios/Source/Common/BaseTableViewCell.swift
  attendance-ios/Source/Common/BaseViewModel.swift
  attendance-ios/Source/Home/HomeAttendanceCheckTableViewCell.swift
  attendance-ios/Source/Home/HomeAttendanceCheckViewController.swift
  attendance-ios/Source/Home/HomeBottomTabView.swift
  attendance-ios/Source/Home/HomeTotalScoreTableViewCell.swift
  attendance-ios/Source/Home/HomeViewController.swift
  attendance-ios/Source/Home/HomeViewModel.swift
Labels: 홈 화면

#57 AttendanceType 모델 수정
  attendance-ios/Source/Model/Attendance.swift
Labels: 파이어베이스

#58 #33 홈화면 오늘 세션 데이터 연동
  attendance-ios.xcodeproj/project.pbxproj
  attendance-ios/Source/Extensions/Date.swift
  attendance-ios/Source/Extensions/UIString.swift
  attendance-ios/Source/Home/HomeViewController.swift
  attendance-ios/Source/Home/HomeViewModel.swift
Labels: 홈 화면, 파이어베이스

#61 #18, #19, #60 출결 점수 화면 구현
  attendance-ios.xcodeproj/project.pbxproj
  attendance-ios/Resource/Font/TextStyle.swift
  attendance-ios/Source/Common/View/BaseNavigationBarView.swift
  attendance-ios/Source/Home/HelpViewController.swift
  attendance-ios/Source/Home/HomeAttendanceCheckTableViewCell.swift
  attendance-ios/Source/Home/HomeAttendanceCheckViewController.swift
  attendance-ios/Source/Home/HomeAttendanceDetailViewController.swift
  attendance-ios/Source/Home/HomeChartView.swift
  attendance-ios/Source/Home/HomeTotalScoreTableViewCell.swift
  attendance-ios/Source/Home/HomeViewController.swift
  attendance-ios/Source/Home/HomeViewModel.swift
  attendance-ios/Source/Home/MKMagneticProgress.swift
  attendance-ios/Source/Setting/SettingPrivacyPolicyViewController.swift
  attendance-ios/Source/Setting/SettingViewController+UI.swift
  attendance-ios/Source/Setting/SettingViewController.swift
  attendance-ios/Source/Setting/SettingViewModel.swift
Labels: 점수 화면
